# Model arguments
model_name_or_path: /scratch/project_462000319/zosaelai2/models/Poro-34b-Chat
torch_dtype: bfloat16

# Data training arguments
#chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
chat_template: "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
dataset_mixer:
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/dolly-fi: 1.0 #15k rows
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/oasst1-fi: 1.0 #20k rows
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/lima-fi: 1.0 #800 rows
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/oasst2: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/turku-paraphrase: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/Capybara-fi-deepl: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/ultrachat_16k_fi_deepl: 0.5
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/argilla/10k_prompts_ranked_mistral_large_responses: 1.0 #5098 examples
dataset_splits:
- train
- test
preprocessing_num_workers: 7

# SFT trainer config
bf16: true
do_eval: true
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-05
log_level: info
log_on_each_node: false
logging_steps: 5
evaluation_strategy: steps
eval_steps: 250
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 3
output_dir: /scratch/project_462000241/villekom/models/alignment_handbook/sft/poro_mixed_full_packing_noglaive
overwrite_output_dir: false
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
push_to_hub: false
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 100
save_total_limit: 2
seed: 42
warmup_ratio: 0.1
packing: true